package com.ravindra.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.ravindra.model.User;
import com.ravindra.model.UserRequest;
import com.ravindra.model.UserResponse;
import com.ravindra.service.IUserService;
import com.ravindra.util.JwtUtil;

@RestController
@RequestMapping("/user")

public class UserController {
	@Autowired
	private IUserService service;
	@Autowired
	private JwtUtil util;
	@Autowired
	private AuthenticationManager authenticationManager;
	//save user data
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user)
	{
		Integer id=service.saveUser(user);
		System.out.println("ravi");
		String body= "User'"+id+"' saved";
		return ResponseEntity.ok(body);
	}
	
	//Validate user and generate token
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request)
	{
		authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
		String token=util.generateToken(request.getUsername());
		
		return ResponseEntity.ok(new UserResponse(token,"Sucess! Generated By RIT-Ravindra"));
	}
	//after login only
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p)
	{
		return ResponseEntity.ok("hello User!"+p.getName());
	}
}
